spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/db/fizz_buzz
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging.config: log4j2.xml
